dist: trusty
sudo: required
git:
  depth: 3
language: ruby
cache: bundler
rvm:
- 2.4.1
addons:
  chrome: stable
env:
  matrix:
  - DB=mysql
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- cd server
- bash scripts/travis-before-install.sh
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- mysql -e 'CREATE DATABASE uofmeme_app_test;'
script:
- whereis google-chrome-stable
- google-chrome-stable --version
- whereis chromedriver
- bundle install --path vendor/cache --quiet
- bash scripts/vagrant-tests.sh
install:
- wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  -P ~/ --quiet
- unzip -q ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
after_success:
- bash scripts/deploy.sh
notifications:
  email: true
