dist: trusty
sudo: required
git:
  depth: 3
language: ruby
cache: bundler
rvm:
- 2.4.1
addons:
  chrome: stable
env:
  matrix:
  - DB=mysql
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- cd server
- bash scripts/install.sh
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- mysql -e 'CREATE DATABASE uofmeme_app_test;'
script:
- whereis google-chrome-stable
- google-chrome-stable --version
- whereis chromedriver
- bundle install --path vendor/cache
- bash scripts/tests.sh
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
install:
- wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: talk2bryan/UofMeme
  bucket: uofmemebucket
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: uofmemebucket
  key: latest.zip
  bundle_type: zip
  application: UofMeme
  deployment_group: master
  region: us-east-2
  on: *2

notifications:
  email: false
  slack:
    secure: TYPYxQMbXXh05KG2o+8Q4RTK61pDBeRoJfNmwQYCPyW5GYTw3NyjNrdXaXe0TLwvKf9vU1lO72LfQXsWPQnLKiFUGBhqnracdPbYdayeCbpYzsjybwPiiuXCuSe4/DLGhuLPTsutF3tq34cA3mZEkBLPieHQAneTAcmKCGRSOgss3G0lzHsgJHAY/tXxj6iqcmMlbUitbXvZJHG5pixGEZyMkvUHXz0rQ0Oka7dsy6Lswpp4LJBCUq3PtrvE4EbclqxAS5i0fIp7FkWa3Ksw3QgR/QUS0NYHFhkjjSqakapHg0VSgfsWQGETlCK1F/wH+woFm3OtlC3zPJ9lPkHPAbH94xpFp1GoRQbRk3eHRt2y0n/OG2MHV4MaGLVq3fH39wwN2jT/bW8gCINP86roYDTF4HmZm03L0AmPAaIULYEJctTPah6yfcj4xhhVCSngA1oe0bYjQkYuMcUEV+H3D/d8r9T10wyWzJB6pULszHQ9Wa75hBqTcDNIopDwJ1ZX1Hza0OCYEkgZuujT4rJ4Wqmpw5MUVFOI4o4BPhN/E4Y6p/C3UxSGfAYvyLUWWsYQmXT9ZdxICA7/DwDe1VEYJ4s9HXPcxFF0PGjv3GKilsSi0ks2HfueybfaK+8riGfZYkak4GkOGJ1zZbfxOj2uWkDjbPBV+MrEJbsSpd+yvNI=
