# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: uofmeme_app_development

test:
  <<: *default
  database: uofmeme_app_test

production:
  <<: *default
  database: uofmeme_app_production
  username: uofmeme_app
  password: <%= ENV['UOFMEME_APP_DATABASE_PASSWORD'] %>

